---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Define nodejs_install_npm_user
  set_fact:
    nodejs_install_npm_user: "{{ ansible_ssh_user }}"
  when: nodejs_install_npm_user is not defined

# TODO: Remove this task after Ansible 2.x npm module bug is fixed. See:
# https://github.com/ansible/ansible-modules-extras/issues/1375
- name: Ensure npm global packages are installed.
  npm:
    name: "{{ item.name }}"
    version: "{{ item.version | default('') }}"
    global: yes
    state: present
  become: yes
  become_user: "{{ nodejs_install_npm_user }}"
  with_items: "{{ nodejs_npm_global_packages }}"

- name: Ensure npm global packages are at the latest release.
  npm:
    name: "{{ item.name }}"
    version: "{{ item.version | default('') }}"
    global: yes
    state: latest
  become: yes
  become_user: "{{ nodejs_install_npm_user }}"
  with_items: "{{ nodejs_npm_global_packages }}"
